name: "Build Flipper App"
on: [push, pull_request]

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    name: 'Build for Latest Unleashed'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
        id: build-app
        with:
          # This URL unlocks the "banned" functions (strtok)
          sdk-index-url: https://up.momentum-fw.dev/firmware/directory.json
          # This targets the NEW firmware that has the missing 'SerialHandle' parts
          sdk-channel: release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: MyFlipperApp
          path: ${{ steps.build-app.outputs.fap-artifacts }}
